:source-language: shell
:source-highlighter: highlight.js
:highlightjsdir: highlight
:doctype: article
//URLS
:url-tmate: https://github.com/tmate-io/tmate
:url-tmux: https://github.com/tmux/tmux/wiki
:url-art-of-command-line: https://github.com/jlevy/the-art-of-command-line


= *Commands*

*These come first, as they tend to be the most useful for me.*

[.normal]
This section is predominantly about moving around in the terminal.

I like to use {url-tmux}[Tmux] as a terminal multiplexer, allowing us to opn multiple panes within our terminal.
We can use a fork of Tmux {url-tmate}[Tmate] which provides an instant pairing solution, we do so by sharing the ssh key of a session created for us when doing `tmux`.
What is very cool is that we can import all of our personalised Tmate keybindings into the session by doing `tmux -f ~/.tmate.conf` (the tmate configuration file is at the root of our local, and is where we put any of our personalized keybindings).

There are all sorts of really great things we can do through the terminal, and I have taken to using it for pretty much everything because it's so efficient (except CSS styling).

A really great resource and general good read for anyone interested in getting to love the terminal is {url-art-of-command-line}[The Art of Command Line].

Otherwise, I use this page to store commands that I have found useful. So it's a: _Work in progress..._

== Vim Commands

For basic commands like moving around (h,j,k,l) see vim tutor.
These commands are slightly more esoteric.
|===
| Command | Action

| `:help [word]`
| then hit `CTRL-D` to see matching help entries for "word".

|`:helpgrep [word]`
|Does the same as above

| `:help`
| To see list of all possible files relating to vim instructions
|===

[discrete]
=== *Navigating Around*

Commands to move around in the vim environment.

.*Window or Pane control*
|===
|Command | Action

|`:split`
|opens a new pane above/below

|`:control w + up arrow`
|switch between these panes

|`:control w + _`
|to make other pane exponentially smaller

|`:control w + =`
|to make panes of equal proportion

|`:control w + -`
|to adjust incrementally proportion of pane

|`:control w + +`
|to make current selected pane bigger
|===

[discrete]
=== *Editing*

.*Useful Vim Keys for editing*

|===
|Command | Action

|`ysw`
|"you surround word"; type this when at the beginning of a word,
                   followed by the character you want to surround it with.
|`ys[n chars]l`
|Surrounds the letter under cursor n times right

|`ys[n chars]h`
|Surrounds the letter under cursor n times left

|`:set spell`
|Spell check (it highlights suspect words)

|`:set nospell`
|Turn off spell checker

|`z=`
|If you're sure its the first one

|`1z=`
|If you're sure its the first one

|`~`
|Capitalize a letter

|`.`
|Do the last command (i.e. Capitalize a letter)

|`/[a word]`
|Highlights searched word

|`ctrl n`
| to select how many times it appears, hit enter, then change the word

|`:noh`
|Remove highlight on word or character until next search

|`:set nohlsearch`
|Turn off highlighting completely

|`gqq`
|Formatting lines (not yet understood).
                    Though https://vim.fandom.com/wiki/Power_of_g[look here] for reference, or https://vim.fandom.com/wiki/Format_only_long_lines#:~:text=The%20normal%2Dmode%20gqq%20command,will%20call%20par%201000%20times.[here], maybe https://vim.fandom.com/wiki/Power_of_g[here]
                    Or https://vim.fandom.com/wiki/Format_only_long_lines#:~:text=The%20normal%2Dmode%20gqq%20command,will%20call%20par%201000%20times.[here]
                    It seems to format lines into sentence widths of 80 characters.
|`shift J`
|Joins the line beneath to current line on.
|===


== Tmux commands

* Commands to move around Tmux environment.

.Window and Pane Management

|===
|Command | Action

|`ctrl -b + c`
|Create new window

|`ctrl -b + n`
|Move to next or previous window

|`ctrl -b + space`
|Reorganise panes, can do repeatedly

|`ctrl -b + z`
|Zoom into one pane, and again to zoom out
|===

* To open a tmate session using tmux configuration do:

.*Tmate session with Tmux configurations*
[sourc, sh]
----
tmate -f ~/.tmux.conf
----

== Shell Commands

`git log [filename]` => if interested in the log history of a specific file
E.G. `git log lib/user.rb`


.*Regenerate on change to generate "book" using asciidoctor*
`find . -name \*.adoc | entr -c asciidoctor book.adoc`
=> it runs continuous updates on a file to the html loaded version (can see in browser after refresh (control R))

Commands use whilst playing around with 'figlet' and 'cowsay'

- Brew search cowsay

You set up the cowsay with brew install and then you pipe something to cows and the cow says it…
Fortune with brew install and you pipe fortune to cowsay
Banner with brew install
figlet
Different font files with figlet
Hippo instead of cow

.*How to read output from a command into VIM*
[source, shell]
----
:r !echo "Zeinzu" | figlet -f isometric1.flf
----

.*Where to find the fonts*
[source, shell]
----
cd /opt/homebrew/Cellar/figlet/2.2.5/share/figlet/fonts
----

.*How to run the test suite in background*

----
ls **/*.rb **/*.erb | entr -r -c rspec
----

It says:
list every file here that has a suffix of .rb or . everything here that has a suffix of .erb
then pipe to it -r and -c with the next command of `rspec`

This is an example, can also use jest, or capyabara, or any other test suite
It continuously listens for something to happen


`Ag -l TODO`
`Ag TODO` will show you exact lines that they’re in

If we mark the TODO within the file immediately then we can actually use it with AG immediately,

.*Resources*


****

[TIP]
====
* https://explainshell.com/explain?cmd=tmux+-f+%7E%2F.tmux.conf[Search Engine for Shell Commands]
====

****


write something here to see change to the article
