===== What is Sinatra?

===== Creating and Authenticating Users

Learn to authenticate users with the database and sessions

===== Storing users in the database

Usually, user account will be stored in a database.
User accounts can also be considered a resource: we can create a new user account (signing up), read its information (account page), update it, etc.


Something to keep in mind when storing user account information, especially when it contains sensitive data (like a password), is encryption.
A password should never be stored in plain text in a database, as even databases can be subjected to security breaches and attacks.

You can use the `bcrypt` gem in Ruby to achieve this. Make sure you store the encrypted password when inserting the user account in the databse,
and check against the correct encrypted value when authenticating the user.

.lib/user_repository.rb
[source, ruby]
----
class UserRepository
  def create(new_user)
    encrypted_password = BCrypt::Password.create(new_user.password)

    sql = '
      INSERT INTO users (email, password)
        VALUES($1, $2);
    '
    sql_params = [
      new_user.email,
      encrypted_password
    ]
  end

  def sign_in(email, submitted_password)
    user = find_by_email(email)

    return nil if user.nil?  <1>

    encrypted_submitted_password = BCrypt::Password.create(submitted_password)

    if user.password == encrypted_submitted_password
      # login success
    else
      # wrong password
    end
  end

  def find_by_email(email)
    # ...
  end
end
----
<1> We should be saying `return nil unless user`

===== On Sessions

By design, web server can't remember information about specific client = it only receives requests, and sends back a response.

In order to keep track about a specific client, we can use a feature of Sinatra called the session. By storing information in the sessoinm we can make it available in any subsequent requests from the same client.

Authentication is a very good example on how sessoins can be useful - here is a typical HTTP flow of a user signing in:

1. The user (through web browser) signs in on a website using their credentials.
2. The web browser send the HTTP request with the credentials to the server.
3. The serve checks the credentials, usually by looking in a ddatabase.
4. If credentials are valid, the server stores information about the signed-in user in the session and sends back the response.
5. During any other request sent by the same client (so, by the same user), the session will contain the user information stored previously.
   For any other client, the sessoin will not contain this information.

So the session is a way to "remember" information about a specific user, even though the client they are using is sending many different requests to the server.

====  Using sessoins in Sinatra

.lib/application.rb
[source, ruby]
----
class Application < Sinatra::Base
  configure :development do
    register Sinatra::Reloader
  end

  # This route simply returns the login page
  get '/login' do
    return erb(:login)
  end

  # This route receives login information (email and password)
  # as body parameters, and find the user in the database
  # using the email. If the password matches, it returns
  # a success page.
  post '/login' do
    email = params[:email]
    password = params[:password]

    user = UserRepository.find_by_email(email)

    # This is a simplified way of
    # checking the password. In a real
    # project, you should encrypt the password
    # stored in the database.
    if user.password == password
      # Set the user ID in session
      session[:user_id] = user.id

      return erb(:login_success)
    else
      return erb(:login_error)
    end
  end

  # This route is an example
  # of a "authenticated-only" route.
  # It can be accessed only if a user is
  # signed-in (if we have user information in session).
  get '/account_page' do
    if session[:user_id] == nil
      # No user id in the session
      # so the user is not logged in.
      return redirect('/login')
    else
      # The user is logged in, display
      # their account page.
      return erb(:account)
    end
  end
end
----

